twig:
  form_themes:
    - "@PushwordAdminBlockEditor/editorjs_widget.html.twig"
  paths:
    "%pw.package_dir%/admin-block-editor/src/../src/templates": Pushword # Permit to access component defined here and in core
