services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $editorBlockForNewPage: "%pw.pushword_admin_block_editor.new_page%"
      $mediaClass: "%pw.entity_media%"
      $pageClass: "%pw.entity_page%"
      $publicMediaDir: "%pw.public_media_dir%"

  Pushword\AdminBlockEditor\:
    resource: "../*"
    exclude: "../{DependencyInjection,Entity,Migrations,Tests,config,Kernel.php,Installer/install.php}"

  Pushword\AdminBlockEditor\Controller\:
    resource: "../Controller/"
    tags: ["controller.service_arguments"]
